### ISSUE TITLE
Resizing window adjusts widgets proportionally

### ISSUE THREAD

**Issue by tdryer** [fltk-rs/fltk-flex#2]
When resizing a window, widgets inside `Flex` are adjusted proportionally (the default behavior of `FL_Group`) rather than maintaining the expected layout with the defined sizes, pads, and margins. This can be observed in any of the examples, and by comparing the equivalent examples from `FL_Flex`.

**Comment by MoAlyousef** [comment]
I have pushed a fix for the overlapping widgets in the demo example.
The thing is that the FL_Flex widget has the advantage of being able to override the resize virtual method, which is called automatically whenever it's resized. I think to get a similar effect on the Rust side, a change needs to be made in fltk-rs itself, basically adding something like a resize_callback() or something to that effect. The closest that can be done currently is to handle the resize event if needed, something like:
```rust
    col.handle(
      move |c, ev| match ev {
      enums::Event::Resize=> {
        c.set_size(630, 470);
        let c = c.clone();
        c.center_of_parent();
        true
      }
      _ => false,
    });
    win.size_range(600, 400, 0, 0);
```
in the login example gives the same effect as the FL_Flex login example. 

Another option is just including Fl_Flex in the fltk-rs wrapper.

**Comment by MoAlyousef** [comment]
I've added a Flex widget in the fltk-rs repo. It's just a wrapper around Fl_Flex. The examples work with minimal modification. 
It's currently in master, and planned for 1.2.0.
https://github.com/fltk-rs/fltk-rs/blob/master/fltk/examples/flex.rs

The main difference is that it doesn't depend on Deref and DerefMut, so passing a Flex to another widget doesn't need `&mut *col` etc. Also the default() constructor initializes the Flex widget to zero size, unlike here where a default constructed Flex widget fills the parent.

**Comment by tdryer** [comment]
Thanks! `fltk::group::Flex` works as expected. The margin and pad isn't configurable like in fltk-flex, but that appears to be a limitation of FL_Flex.

**Comment by MoAlyousef** [comment]
Yes. I've opened a pull request in the FL_FLex repo to expose them.

**Comment by MoAlyousef** [comment]
Sorry, forgot to address this issue :)
So the padding and margins are now exposed since fltk version > 1.2.3
